# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: b4675f8c1426906ff25dbf5dc703facd391360da $
Configuration parameters:
  url = http://it.tuttorotto.eu/
  name = wikitolearn

Please do not commit this to the Git repository! < lol, too late sorry, I HAVE to do this.
"""

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'wikitolearn'
        self.langs = {
            'it': 'it.tuttorotto.eu',
        }

    def scriptpath(self, code):
        return {
            'it': '',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'it': u'1.25.2',
        }[code]

    def protocol(self, code):
        return {
            'it': u'http',
        }[code]
